In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("Sales_Performance_Data.csv")

In [4]:
df.head()

,Order_ID,Order_Date,Customer_Name,Region,State,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales
0,ORD0208,2025-01-01,Customer 147,South,Kerala,Accessories,Backpack,8,1885.11,15,12818.75
1,ORD0066,2025-01-01,Customer 131,South,Kerala,Furniture,Sofa,8,26286.52,10,189262.94
2,ORD0069,2025-01-01,Customer 117,East,Bihar,Accessories,Mouse,9,859.22,5,7346.33
3,ORD0129,2025-01-02,Customer 129,North,Haryana,Office Supplies,Calculator,3,658.64,10,1778.33
4,ORD0152,2025-01-03,Customer 173,South,Tamil Nadu,Furniture,Bookshelf,4,6747.09,5,25638.94

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          500 non-null    str
 1   Order_Date        500 non-null    str
 2   Customer_Name     500 non-null    str
 3   Region            500 non-null    str
 4   State             500 non-null    str
 5   Product_Category  500 non-null    str
 6   Product_Name      500 non-null    str
 7   Quantity          500 non-null    int64
 8   Unit_Price        500 non-null    float64
 9   Discount          500 non-null    int64
 10  Sales             500 non-null    float64
dtypes: float64(2), int64(2), str(7)
memory usage: 43.1 KB

In [6]:
df.describe(include="all")

,Order_ID,Order_Date,Customer_Name,Region,State,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Sales
count,500,500,500,500,500,500,500,500.000000,500.00000,500.000000,500.000000
unique,500,256,184,5,19,4,16,NaN,NaN,NaN,NaN
top,ORD0208,2025-06-11,Customer 170,East,Uttar Pradesh,Electronics,Smartphone,NaN,NaN,NaN,NaN
freq,1,6,9,109,41,172,47,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.426000,15302.50188,8.790000,73845.114000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.863026,18680.85030,5.228822,104146.558335
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,169.39000,0.000000,152.450000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,1277.52500,5.000000,5531.270000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,8130.42000,10.000000,28232.020000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,25971.51250,10.000000,105760.350000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,70143.33000,20.000000,614954.660000

In [7]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
Region              0
State               0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount            0
Sales               0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
# Convert Order_Date into datetime format
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [10]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
Region              0
State               0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount            0
Sales               0
dtype: int64

In [11]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [12]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'region', 'state',
       'product_category', 'product_name', 'quantity', 'unit_price',
       'discount', 'sales'],
      dtype='str')

In [13]:
# Create useful sales-analysis columns
df["order_year"] = df["order_date"].dt.year
df["order_month"] = df["order_date"].dt.month
df["order_month_name"] = df["order_date"].dt.month_name()

In [14]:
df[['order_date','order_year','order_month','order_month_name']].head(10)

  order_date  order_year  order_month order_month_name
0 2025-01-01        2025            1          January
1 2025-01-01        2025            1          January
2 2025-01-01        2025            1          January
3 2025-01-02        2025            1          January
4 2025-01-03        2025            1          January
5 2025-01-04        2025            1          January
6 2025-01-04        2025            1          January
7 2025-01-04        2025            1          January
8 2025-01-05        2025            1          January
9 2025-01-06        2025            1          January

In [15]:
# Calculate the gross sales before discount
df["gross_sales"] = df["quantity"] * df["unit_price"]

In [16]:
df[['quantity','unit_price','gross_sales','discount','sales']].head(10)

   quantity  unit_price  gross_sales  discount      sales
0         8     1885.11     15080.88        15   12818.75
1         8    26286.52    210292.16        10  189262.94
2         9      859.22      7732.98         5    7346.33
3         3      658.64      1975.92        10    1778.33
4         4     6747.09     26988.36         5   25638.94
5         7    13368.37     93578.59        10   84220.73
6        10    22003.66    220036.60        10  198032.94
7         2     3653.39      7306.78         5    6941.44
8         6    11290.85     67745.10        15   57583.34
9         8    22693.30    181546.40        20  145237.12

In [17]:
# Calculate discount amount
df["discount_amount"] = df["gross_sales"] * df["discount"] / 100

In [18]:
df[['gross_sales','discount','discount_amount','sales']].head(10)

   gross_sales  discount  discount_amount      sales
0     15080.88        15         2262.132   12818.75
1    210292.16        10        21029.216  189262.94
2      7732.98         5          386.649    7346.33
3      1975.92        10          197.592    1778.33
4     26988.36         5         1349.418   25638.94
5     93578.59        10         9357.859   84220.73
6    220036.60        10        22003.660  198032.94
7      7306.78         5          365.339    6941.44
8     67745.10        15        10161.765   57583.34
9    181546.40        20        36309.280  145237.12

In [19]:
# Check whether calculated net sales matches the Sales column
df["calculated_sales"] = (df["gross_sales"] - df["discount_amount"]).round(2)
(df["calculated_sales"] == df["sales"].round(2)).all()

np.False_

In [20]:
# Create a sales performance category
df["sales_performance"] = pd.qcut(
    df["sales"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

In [21]:
df[['sales','sales_performance']].head(10)

       sales sales_performance
0   12818.75            Medium
1  189262.94         Very High
2    7346.33            Medium
3    1778.33               Low
4   25638.94            Medium
5   84220.73              High
6  198032.94         Very High
7    6941.44            Medium
8   57583.34              High
9  145237.12         Very High

In [22]:
# Check final dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           500 non-null    str
 1   order_date         500 non-null    datetime64[us]
 2   customer_name      500 non-null    str
 3   region             500 non-null    str
 4   state              500 non-null    str
 5   product_category   500 non-null    str
 6   product_name       500 non-null    str
 7   quantity           500 non-null    int64
 8   unit_price         500 non-null    float64
 9   discount           500 non-null    int64
 10  sales              500 non-null    float64
 11  order_year         500 non-null    int32
 12  order_month        500 non-null    int32
 13  order_month_name   500 non-null    str
 14  gross_sales        500 non-null    float64
 15  discount_amount    500 non-null    float64
 16  calculated_sales   500 non-null    float64
 17  sales_performance  500 non-null    category
dtypes: category(1), datetime64[us](1), float64(5), int32(2), int64(2), str(7)
memory usage: 63.3 KB

In [23]:
# Save cleaned/transformed dataset
df.to_csv("Sales_Performance_Cleaned.csv", index=False)

In [24]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'region', 'state',
       'product_category', 'product_name', 'quantity', 'unit_price',
       'discount', 'sales', 'order_year', 'order_month', 'order_month_name',
       'gross_sales', 'discount_amount', 'calculated_sales',
       'sales_performance'],
      dtype='str')