In [28]:
import pandas as pd

In [29]:
df = pd.read_excel("Student data for pandas project.xlsx")

In [30]:
df

   Student_ID   Name   Maths  Science  English
0           1   Aman      21       54       86
1           2  Mohan      26       25       83
2           3   Rohan     87       20       62
3           4    Syam     70       88       10
4           5     Ram     50       33       75
5           6    Ranu     84       57       73
6           7    Lalu     89       95       47
7           8    Balu     99       44       93
8           9    Kalu      4       74       26
9          10    Talu     70       53       55

In [31]:
df.head(8)

   Student_ID   Name   Maths  Science  English
0           1   Aman      21       54       86
1           2  Mohan      26       25       83
2           3   Rohan     87       20       62
3           4    Syam     70       88       10
4           5     Ram     50       33       75
5           6    Ranu     84       57       73
6           7    Lalu     89       95       47
7           8    Balu     99       44       93

In [32]:
df["Maths"]

0    21
1    26
2    87
3    70
4    50
5    84
6    89
7    99
8     4
9    70
Name: Maths, dtype: int64

In [33]:
df["English"]

0    86
1    83
2    62
3    10
4    75
5    73
6    47
7    93
8    26
9    55
Name: English, dtype: int64

In [34]:
df["Total"] = df["Maths"] + df["English"] + df["Science"]

In [35]:
df["Total"]

0    161
1    134
2    169
3    168
4    158
5    214
6    231
7    236
8    104
9    178
Name: Total, dtype: int64

In [36]:
df

   Student_ID   Name   Maths  Science  English  Total
0           1   Aman      21       54       86    161
1           2  Mohan      26       25       83    134
2           3   Rohan     87       20       62    169
3           4    Syam     70       88       10    168
4           5     Ram     50       33       75    158
5           6    Ranu     84       57       73    214
6           7    Lalu     89       95       47    231
7           8    Balu     99       44       93    236
8           9    Kalu      4       74       26    104
9          10    Talu     70       53       55    178

In [37]:
# df["Average"] = df["Total"]/3

In [38]:
df

   Student_ID   Name   Maths  Science  English  Total
0           1   Aman      21       54       86    161
1           2  Mohan      26       25       83    134
2           3   Rohan     87       20       62    169
3           4    Syam     70       88       10    168
4           5     Ram     50       33       75    158
5           6    Ranu     84       57       73    214
6           7    Lalu     89       95       47    231
7           8    Balu     99       44       93    236
8           9    Kalu      4       74       26    104
9          10    Talu     70       53       55    178

In [39]:
df

   Student_ID   Name   Maths  Science  English  Total
0           1   Aman      21       54       86    161
1           2  Mohan      26       25       83    134
2           3   Rohan     87       20       62    169
3           4    Syam     70       88       10    168
4           5     Ram     50       33       75    158
5           6    Ranu     84       57       73    214
6           7    Lalu     89       95       47    231
7           8    Balu     99       44       93    236
8           9    Kalu      4       74       26    104
9          10    Talu     70       53       55    178

In [40]:
df["Average"] = df["Total"]/3

In [41]:
df

   Student_ID   Name   Maths  Science  English  Total    Average
0           1   Aman      21       54       86    161  53.666667
1           2  Mohan      26       25       83    134  44.666667
2           3   Rohan     87       20       62    169  56.333333
3           4    Syam     70       88       10    168  56.000000
4           5     Ram     50       33       75    158  52.666667
5           6    Ranu     84       57       73    214  71.333333
6           7    Lalu     89       95       47    231  77.000000
7           8    Balu     99       44       93    236  78.666667
8           9    Kalu      4       74       26    104  34.666667
9          10    Talu     70       53       55    178  59.333333

In [42]:
print("Hieghest Marks in maths  :", df["Maths"].max())
print("Hieghest Marks in English  :", df["English"].max())
print("Hieghest Marks in Science  :", df["Science"].max())

Hieghest Marks in maths  : 99
Hieghest Marks in English  : 93
Hieghest Marks in Science  : 95

In [43]:
print("Lowest marks in maths  :" , df["Maths"].min())
print("Lowest marks in English  :" , df["English"].min())
print("Lowest marks in Science  :" , df["Science"].min())

Lowest marks in maths  : 4
Lowest marks in English  : 10
Lowest marks in Science  : 20

In [44]:
print(df.columns)

Index(['Student_ID', 'Name ', 'Maths', 'Science', 'English', 'Total',
       'Average'],
      dtype='str')

In [45]:
topper = df.loc[df["Maths"].idxmax()]
print(topper["Maths"])
print(df.index[df["Maths"].idxmax()])

99
7

In [46]:
df

   Student_ID   Name   Maths  Science  English  Total    Average
0           1   Aman      21       54       86    161  53.666667
1           2  Mohan      26       25       83    134  44.666667
2           3   Rohan     87       20       62    169  56.333333
3           4    Syam     70       88       10    168  56.000000
4           5     Ram     50       33       75    158  52.666667
5           6    Ranu     84       57       73    214  71.333333
6           7    Lalu     89       95       47    231  77.000000
7           8    Balu     99       44       93    236  78.666667
8           9    Kalu      4       74       26    104  34.666667
9          10    Talu     70       53       55    178  59.333333

In [47]:
print(df.head())

   Student_ID   Name   Maths  Science  English  Total    Average
0           1   Aman      21       54       86    161  53.666667
1           2  Mohan      26       25       83    134  44.666667
2           3   Rohan     87       20       62    169  56.333333
3           4    Syam     70       88       10    168  56.000000
4           5     Ram     50       33       75    158  52.666667

In [48]:
# Strip hidden spaces from column names
df.columns = df.columns.str.strip()

# Your original code will now work perfectly
print("Maths Topper")
print(df.loc[df["Maths"].idxmax(), ["Name", "Maths"]])

print("\nEnglish Topper")
print(df.loc[df["English"].idxmax(), ["Name", "English"]])

print("\nScience Topper")
print(df.loc[df["Science"].idxmax(), ["Name", "Science"]])

Maths Topper
Name     Balu
Maths      99
Name: 7, dtype: object

English Topper
Name       Balu
English      93
Name: 7, dtype: object

Science Topper
Name       Lalu
Science      95
Name: 6, dtype: object

In [49]:
def grade(avg):
    if avg >=85:
        return "A"
    elif avg >=70:
        return "B"
    else:
        return "C"
    
df["Grade"] = df["Average"].apply(grade)

In [50]:
df

   Student_ID    Name  Maths  Science  English  Total    Average Grade
0           1   Aman      21       54       86    161  53.666667     C
1           2  Mohan      26       25       83    134  44.666667     C
2           3   Rohan     87       20       62    169  56.333333     C
3           4    Syam     70       88       10    168  56.000000     C
4           5     Ram     50       33       75    158  52.666667     C
5           6    Ranu     84       57       73    214  71.333333     B
6           7    Lalu     89       95       47    231  77.000000     B
7           8    Balu     99       44       93    236  78.666667     B
8           9    Kalu      4       74       26    104  34.666667     C
9          10    Talu     70       53       55    178  59.333333     C

In [53]:
Weak_students = df[df["Average"] < 50]
print("Needs Improvment : \n" , Weak_students)

Needs Improvment :
    Student_ID    Name  Maths  Science  English  Total    Average Grade
1           2  Mohan      26       25       83    134  44.666667     C
8           9    Kalu      4       74       26    104  34.666667     C

In [54]:
print(df)

   Student_ID    Name  Maths  Science  English  Total    Average Grade
0           1   Aman      21       54       86    161  53.666667     C
1           2  Mohan      26       25       83    134  44.666667     C
2           3   Rohan     87       20       62    169  56.333333     C
3           4    Syam     70       88       10    168  56.000000     C
4           5     Ram     50       33       75    158  52.666667     C
5           6    Ranu     84       57       73    214  71.333333     B
6           7    Lalu     89       95       47    231  77.000000     B
7           8    Balu     99       44       93    236  78.666667     B
8           9    Kalu      4       74       26    104  34.666667     C
9          10    Talu     70       53       55    178  59.333333     C

In [55]:
df.to_csv("Student_perfomence_PowerBI.csv" , index=False)